const imagesNames = [
  "butelka1.jpg",
  "butelka2.jpg",
  "butelka3.jpg",
  "ewangelion1.jpg",
  "ewangelion2.jpg",
  "harrypotter1.jpg",
  "harrypotter2.jpg",
  "harrypotter3.jpg",
  "hdmi1.jpg",
  "hdmi2.jpg",
  "hdmi3.jpg",
  "nawoz1.jpg",
  "nawoz2.jpg",
  "nawoz3.jpg",
  "opelek1.PNG",
  "opelek2.PNG",
  "opelek3.PNG",
  "toaster1.PNG",
  "toaster2.PNG",
  "toaster3.PNG",
  "samochod0.jpg",
  "samochod1.jpg",
  "samochod2.jpg",
  "tinhifi1.jpg",
  "tinhifi2.jpg",
  "tinhifi3.jpg",
  "wasy1.jpg",
  "wasy2.jpg",
];

export default imagesNames;
